"""Every format the uploader advertises has to be readable, from a real file.

THE FINDING. The uploader, `ALLOWED_EXTENSIONS` and `SUPPORTED_EXTENSIONS` all
admit `.xls`, and a public deployment lists it. `ExcelReaderSkill` sent every
non-CSV file to openpyxl, which cannot read the legacy format at all:

    openpyxl does not support the old .xls file format, please use xlrd to
    read this file, or convert it to the more recent .xlsx file format.

So every real `.xls` failed at parsing, and the agent then replaced that
sentence with "Parsing failed", which is all the user was shown.

`samples/sample_sales.xls` is a genuine BIFF8 workbook, written by Excel 16.0
(`SaveAs FileFormat=56`) from `samples/sample_sales.xlsx`. It cannot be
regenerated by `make_samples.py`, which has no .xls writer; hence the test that
it really is one, since a renamed .xlsx would prove nothing.

Checked by hand at the same time, and not repeated here because it needs the
transcription API: all six advertised audio containers (wav, mp3, m4a, flac,
ogg, webm), re-encoded from `samples/sample_audio.wav`, transcribe to the same
390 characters. PDF, .xlsx and CSV in UTF-8 and cp1252 all parse. `.xls` was
the only format accepted and unreadable.

Run:
    pytest tests/test_advertised_formats.py -v
"""

from __future__ import annotations

import re
from pathlib import Path

import pandas as pd
import pytest

from agents.document_agent import SUPPORTED_EXTENSIONS
from core.models import SkillInput
from skills.excel_reader_skill import ExcelReaderSkill
from skills.pdf_reader_skill import PDFReaderSkill
from utils.file_handler import ALLOWED_EXTENSIONS

ROOT = Path(__file__).resolve().parents[1]
SAMPLES = ROOT / "tests" / "e2e" / "samples"
OLE2_MAGIC = bytes.fromhex("d0cf11e0a1b11ae1")


def _advertised() -> set:
    source = (ROOT / "ui" / "app.py").read_text(encoding="utf-8")
    listed = re.search(r"file_uploader\(.*?type=\[(.*?)\]", source, re.S).group(1)
    return {"." + item.strip().strip('"\'') for item in listed.split(",")}


def test_the_uploader_the_validator_and_the_agent_agree():
    """Three lists decide what a user may upload and what the agent will try.
    One advertising a format another cannot route is how an upload reaches a
    reader that was never meant for it."""
    assert _advertised() == ALLOWED_EXTENSIONS == set(SUPPORTED_EXTENSIONS)


def test_the_xls_fixture_is_a_real_legacy_workbook():
    raw = (SAMPLES / "sample_sales.xls").read_bytes()
    assert raw[:8] == OLE2_MAGIC, "not an OLE2 compound document, so not a real .xls"


def _csv(tmp_path: Path) -> Path:
    path = tmp_path / "sample_sales.csv"
    pd.read_excel(SAMPLES / "sample_sales.xlsx").to_csv(path, index=False)
    return path


@pytest.mark.parametrize("name, reader, make", [
    ("pdf", PDFReaderSkill, lambda tmp: SAMPLES / "sample_report.pdf"),
    ("xlsx", ExcelReaderSkill, lambda tmp: SAMPLES / "sample_sales.xlsx"),
    ("csv", ExcelReaderSkill, _csv),
    pytest.param("xls", ExcelReaderSkill, lambda tmp: SAMPLES / "sample_sales.xls",
                 marks=pytest.mark.xfail(strict=True, reason=(
                     "openpyxl cannot read BIFF8; the reader has no .xls engine"))),
])
def test_a_real_file_of_each_advertised_document_format_parses(name, reader, make, tmp_path):
    path = make(tmp_path)
    out = reader(config={}).safe_execute(SkillInput(data={"file_path": str(path)}))
    assert out.success, out.error
    assert out.data.full_text.strip()
